D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV6["culebre"], "culebre.openstreetmap.org."),
  PTR(IPV6["fafnir"], "fafnir.openstreetmap.org."),
  PTR(IPV6["fume"], "fume.openstreetmap.org."),
  PTR(IPV6["grisu"], "grisu.openstreetmap.org."),
  PTR(IPV6["horntail"], "horntail.openstreetmap.org."),
  PTR(IPV6["idris"], "idris.openstreetmap.org."),
  PTR(IPV6["konqi"], "konqi.openstreetmap.org."),
  PTR(IPV6["longma"], "longma.openstreetmap.org."),
  PTR(IPV6["muirdris"], "muirdris.openstreetmap.org."),
  PTR(IPV6["naga"], "naga.openstreetmap.org."),
  PTR(IPV6["smaug"], "smaug.openstreetmap.org."),
  PTR(IPV6["spike-01"], "spike-01.openstreetmap.org."),
  PTR(IPV6["spike-02"], "spike-02.openstreetmap.org."),
  PTR(IPV6["spike-03"], "spike-03.openstreetmap.org."),
  PTR(IPV6["switch1.dub"], "switch1.dub.openstreetmap.org.")
);
