D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV6["culebre.he"], "culebre.he.openstreetmap.org."),
  PTR(IPV6["fafnir.he"], "fafnir.he.openstreetmap.org."),
  PTR(IPV6["fume.he"], "fume.he.openstreetmap.org."),
  PTR(IPV6["grisu.he"], "grisu.he.openstreetmap.org."),
  PTR(IPV6["horntail.he"], "horntail.he.openstreetmap.org."),
  PTR(IPV6["idris.he"], "idris.he.openstreetmap.org."),
  PTR(IPV6["konqi.he"], "konqi.he.openstreetmap.org."),
  PTR(IPV6["longma.he"], "longma.he.openstreetmap.org."),
  PTR(IPV6["muirdris.he"], "muirdris.he.openstreetmap.org."),
  PTR(IPV6["naga.he"], "naga.he.openstreetmap.org."),
  PTR(IPV6["smaug.he"], "smaug.he.openstreetmap.org."),
  PTR(IPV6["spike-01.he"], "spike-01.he.openstreetmap.org."),
  PTR(IPV6["spike-02.he"], "spike-02.he.openstreetmap.org."),
  PTR(IPV6["spike-03.he"], "spike-03.he.openstreetmap.org."),
  PTR(IPV6["switch1.he.dub"], "switch1.he.dub.openstreetmap.org.")
);
