D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV4["culebre"], "culebre.openstreetmap.org."),
  PTR(IPV4["fafnir"], "fafnir.openstreetmap.org."),
  PTR(IPV4["fume"], "fume.openstreetmap.org."),
  PTR(IPV4["grisu"], "grisu.openstreetmap.org."),
  PTR(IPV4["horntail"], "horntail.openstreetmap.org."),
  PTR(IPV4["idris"], "idris.openstreetmap.org."),
  PTR(IPV4["konqi"], "konqi.openstreetmap.org."),
  PTR(IPV4["longma"], "longma.openstreetmap.org."),
  PTR(IPV4["muirdris"], "muirdris.openstreetmap.org."),
  PTR(IPV4["naga"], "naga.openstreetmap.org."),
  PTR(IPV4["smaug"], "smaug.openstreetmap.org."),
  PTR(IPV4["spike-01"], "spike-01.openstreetmap.org."),
  PTR(IPV4["spike-02"], "spike-02.openstreetmap.org."),
  PTR(IPV4["spike-03"], "spike-03.openstreetmap.org."),
  PTR(IPV4["switch1.dub"], "switch1.dub.openstreetmap.org."),
);
