D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(CULEBRE_IPV6, "culebre.openstreetmap.org."),
  PTR(FAFNIR_IPV6, "fafnir.openstreetmap.org."),
  PTR(GORWEN_IPV6, "gorwen.openstreetmap.org."),
  PTR(HORNTAIL_IPV6, "horntail.openstreetmap.org."),
  PTR(IDRIS_IPV6, "idris.openstreetmap.org."),
  PTR(JAKELONG_IPV6, "jakelong.openstreetmap.org."),
  PTR(KONQI_IPV6, "konqi.openstreetmap.org."),
  PTR(LONGMA_IPV6, "longma.openstreetmap.org."),
  PTR(MUIRDRIS_IPV6.split(".").pop(), "muirdris.openstreetmap.org."),
  PTR(NAGA_IPV6, "naga.openstreetmap.org."),
  PTR(SMAUG_IPV6.split(".").pop(), "smaug.openstreetmap.org."),
  PTR(SPIKE01_IPV6, "spike-01.openstreetmap.org."),
  PTR(SPIKE02_IPV6, "spike-02.openstreetmap.org."),
  PTR(SPIKE03_IPV6, "spike-03.openstreetmap.org."),
  PTR(SWITCH1DUB_IPV6, "switch1.dub.openstreetmap.org.")
);
