D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(SWITCH1DUB_IPV4, "switch1.dub.openstreetmap.org."),
  PTR(FAFNIR_IPV4, "fafnir.openstreetmap.org."),
  PTR(SPIKE01_IPV4, "spike-01.openstreetmap.org."),
  PTR(SPIKE02_IPV4, "spike-02.openstreetmap.org."),
  PTR(SPIKE03_IPV4, "spike-03.openstreetmap.org."),
  PTR(IDRIS_IPV4, "idris.openstreetmap.org."),
  PTR(KONQI_IPV4, "konqi.openstreetmap.org."),
  PTR(NAGA_IPV4, "naga.openstreetmap.org."),
  PTR(CULEBRE_IPV4, "culebre.openstreetmap.org."),
  PTR(HORNTAIL_IPV4, "horntail.openstreetmap.org."),
  PTR(GORWEN_IPV4, "gorwen.openstreetmap.org."),
  PTR(JAKELONG_IPV4, "jakelong.openstreetmap.org."),
  PTR(LONGMA_IPV4, "longma.openstreetmap.org.")
);
