D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV6["dribble.he"], "dribble.he.openstreetmap.org."),
  PTR(IPV6["dulcy.he"], "dulcy.he.openstreetmap.org."),
  PTR(IPV6["faffy.he"], "faffy.he.openstreetmap.org."),
  PTR(IPV6["lockheed.he"], "lockheed.he.openstreetmap.org."),
  PTR(IPV6["norbert.he"], "norbert.he.openstreetmap.org."),
  PTR(IPV6["odin.he"], "odin.he.openstreetmap.org."),
  PTR(IPV6["spike-06.he"], "spike-06.he.openstreetmap.org."),
  PTR(IPV6["spike-07.he"], "spike-07.he.openstreetmap.org."),
  PTR(IPV6["spike-08.he"], "spike-08.he.openstreetmap.org."),
  PTR(IPV6["tabaluga.he"], "tabaluga.he.openstreetmap.org."),
  PTR(IPV6["vhagar.he"], "vhagar.he.openstreetmap.org."),
  PTR(IPV6["switch1.he.ams"], "switch1.he.ams.openstreetmap.org."),
);
