D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV4["dribble.he"], "dribble.he.openstreetmap.org."),
  PTR(IPV4["dulcy.he"], "dulcy.he.openstreetmap.org."),
  PTR(IPV4["faffy.he"], "faffy.he.openstreetmap.org."),
  PTR(IPV4["lockheed.he"], "lockheed.he.openstreetmap.org."),
  PTR(IPV4["norbert.he"], "norbert.he.openstreetmap.org."),
  PTR(IPV4["odin.he"], "odin.he.openstreetmap.org."),
  PTR(IPV4["spike-06.he"], "spike-06.he.openstreetmap.org."),
  PTR(IPV4["spike-07.he"], "spike-07.he.openstreetmap.org."),
  PTR(IPV4["spike-08.he"], "spike-08.he.openstreetmap.org."),
  PTR(IPV4["tabaluga.he"], "tabaluga.he.openstreetmap.org."),
  PTR(IPV4["vhagar.he"], "vhagar.he.openstreetmap.org."),
  PTR(IPV4["switch1.he.ams"], "switch1.he.ams.openstreetmap.org."),
);
