D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV6["dribble"], "dribble.openstreetmap.org."),
  PTR(IPV6["dulcy"], "dulcy.openstreetmap.org."),
  PTR(IPV6["faffy"], "faffy.openstreetmap.org."),
  PTR(IPV6["lockheed"], "lockheed.openstreetmap.org."),
  PTR(IPV6["norbert"], "norbert.openstreetmap.org."),
  PTR(IPV6["odin"], "odin.openstreetmap.org."),
  PTR(IPV6["spike-06"], "spike-06.openstreetmap.org."),
  PTR(IPV6["spike-07"], "spike-07.openstreetmap.org."),
  PTR(IPV6["spike-08"], "spike-08.openstreetmap.org."),
  PTR(IPV6["tabaluga"], "tabaluga.openstreetmap.org."),
  PTR(IPV6["vhagar"], "vhagar.openstreetmap.org."),
  PTR(IPV6["switch1.ams"], "switch1.ams.openstreetmap.org."),
);
