D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV6["culebre.he"], "culebre.openstreetmap.org."),
  PTR(IPV6["fafnir.he"], "fafnir.openstreetmap.org."),
  PTR(IPV6["fume.he"], "fume.openstreetmap.org."),
  PTR(IPV6["grisu.he"], "grisu.openstreetmap.org."),
  PTR(IPV6["horntail.he"], "horntail.openstreetmap.org."),
  PTR(IPV6["idris.he"], "idris.openstreetmap.org."),
  PTR(IPV6["konqi.he"], "konqi.openstreetmap.org."),
  PTR(IPV6["longma.he"], "longma.openstreetmap.org."),
  PTR(IPV6["muirdris.he"], "muirdris.openstreetmap.org."),
  PTR(IPV6["naga.he"], "naga.openstreetmap.org."),
  PTR(IPV6["smaug.he"], "smaug.openstreetmap.org."),
  PTR(IPV6["spike-01.he"], "spike-01.openstreetmap.org."),
  PTR(IPV6["spike-02.he"], "spike-02.openstreetmap.org."),
  PTR(IPV6["spike-03.he"], "spike-03.openstreetmap.org."),
  PTR(IPV6["switch1.he.dub"], "switch1.dub.openstreetmap.org.")
);
