D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(IPV4["dribble"], "dribble.openstreetmap.org."),
  PTR(IPV4["dulcy"], "dulcy.openstreetmap.org."),
  PTR(IPV4["faffy"], "faffy.openstreetmap.org."),
  PTR(IPV4["lockheed"], "lockheed.openstreetmap.org."),
  PTR(IPV4["norbert"], "norbert.openstreetmap.org."),
  PTR(IPV4["odin"], "odin.openstreetmap.org."),
  PTR(IPV4["spike-06"], "spike-06.openstreetmap.org."),
  PTR(IPV4["spike-07"], "spike-07.openstreetmap.org."),
  PTR(IPV4["spike-08"], "spike-08.openstreetmap.org."),
  PTR(IPV4["tabaluga"], "tabaluga.openstreetmap.org."),
  PTR(IPV4["vhagar"], "vhagar.openstreetmap.org."),
  PTR(IPV4["switch1.ams"], "switch1.ams.openstreetmap.org."),
);
