D(DOMAIN, REGISTRAR, DnsProvider(PROVIDER),
  PTR(CULEBRE_IPV6_HE, "culebre.openstreetmap.org."),
  PTR(FAFNIR_IPV6_HE, "fafnir.openstreetmap.org."),
  PTR(FUME_IPV6_HE, "fume.openstreetmap.org."),
  PTR(GRISU_IPV6_HE, "grisu.openstreetmap.org."),
  PTR(HORNTAIL_IPV6_HE, "horntail.openstreetmap.org."),
  PTR(IDRIS_IPV6_HE, "idris.openstreetmap.org."),
  PTR(KONQI_IPV6_HE, "konqi.openstreetmap.org."),
  PTR(LONGMA_IPV6_HE, "longma.openstreetmap.org."),
  PTR(MUIRDRIS_IPV6_HE.split(".").pop(), "muirdris.openstreetmap.org."),
  PTR(NAGA_IPV6_HE, "naga.openstreetmap.org."),
  PTR(SMAUG_IPV6_HE.split(".").pop(), "smaug.openstreetmap.org."),
  PTR(SPIKE01_IPV6_HE, "spike-01.openstreetmap.org."),
  PTR(SPIKE02_IPV6_HE, "spike-02.openstreetmap.org."),
  PTR(SPIKE03_IPV6_HE, "spike-03.openstreetmap.org."),
  PTR(SWITCH1DUB_IPV6_HE, "switch1.dub.openstreetmap.org.")
);
